# Generated by Django 5.0.7 on 2024-07-27 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('board_rows', models.IntegerField(default=10)),
                ('board_cols', models.IntegerField(default=10)),
                ('ships_form', models.TextField(blank=True, default=None, null=True)),
                ('resettable', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('key', models.CharField(max_length=10)),
                ('play_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='GamesSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Game Summary',
                'verbose_name_plural': 'Games Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('battleship_api.game',),
        ),
        migrations.CreateModel(
            name='Play',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shot_row', models.IntegerField(default=0)),
                ('shot_col', models.IntegerField(default=0)),
                ('result', models.IntegerField(default=None, null=True)),
                ('is_valid', models.BooleanField(default=True)),
                ('error_type', models.CharField(choices=[('O', 'OUT OF BOUNDS'), ('R', 'REPEATED')], default=None, max_length=1, null=True)),
                ('finished', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='battleship_api.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plays', to='battleship_api.player')),
            ],
        ),
        migrations.CreateModel(
            name='Ship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.TextField()),
                ('row', models.IntegerField(default=0)),
                ('col', models.IntegerField(default=0)),
                ('turn', models.IntegerField(default=0)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ships', to='battleship_api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('games', models.ManyToManyField(blank=True, related_name='tournaments', to='battleship_api.game')),
                ('players', models.ManyToManyField(blank=True, related_name='players', to='battleship_api.player')),
            ],
        ),
    ]
